---

port: 4004
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, private.cfg, "temp", "archives", "casks"]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Nerd Fonts - Iconic font aggregator, collection, and patcher"
keywords:    "fonts collection patched-fonts powerline shell statusline python iconic-fonts patcher FontForge font-awesome octicons font-linux SourceCodePro Hack Droid Sans Meslo AnonymousPro ProFont Inconsolata"
description: "Iconic font aggregator, collection, and patcher: 3,600+ glyph/icons, 40+ patched fonts: Hack, Source Code Pro, and many more. Popular glyph collections: Font Awesome, Octicons, and many more"
source_link: "https://github.com/ryanoasis/nerd-fonts/tree/gh-pages"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: "UA-91070609-1"


### template colors, used site-wide via css ###
colors:
  black:         '#111111'
  gray:          '#75715e'
  white:         '#f8f8f8'
  purewhite:     '#ffffff'
  blue:          '#49a7e9'
  green:         '#9bcf2f'
  purple:        '#c869bf'
  orange:        '#fab125'
  turquoise:     '#0fbfcf'
  yellow:        '#ffce3e'
  red:           '#de3c3c'

kramdown:
  auto_ids:  false

